#!/bin/sh
# This file brought to you by https://stackoverflow.com/questions/2293498/git-commit-hooks-global-settings
# and https://stackoverflow.com/questions/15015894/git-add-signed-off-by-line-using-format-signoff-not-working

NAME=$(git config user.name)
EMAIL=$(git config user.email)

if [ -z "$NAME" ]; then
    echo "empty git config user.name"
    exit 1
fi

if [ -z "$EMAIL" ]; then
    echo "empty git config user.email"
    exit 1
fi

git interpret-trailers --if-exists doNothing --trailer \
    "Signed-off-by: $NAME <$EMAIL>" \
    --in-place "$1"
