" Auto-install vim-plug if not present
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Plugins
call plug#begin()
Plug 'morhetz/gruvbox'           " your beloved color scheme
Plug 'elzr/vim-json'             " better JSON highlighting
call plug#end()

syntax on
set nocompatible
filetype plugin indent on

" Gruvbox settings
set background=dark
let g:gruvbox_contrast_dark = 'medium'
silent! colorscheme gruvbox      " silent! prevents error if not yet installed

" Sane defaults
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set number
set ruler
set showcmd
set incsearch
set hlsearch
set ignorecase
set smartcase
set backspace=indent,eol,start

" No annoying swap files
set noswapfile
set nobackup

" Mouse support
set mouse=a
