
# tap repositories and their packages

tap homebrew/core
brew act
brew antigen
brew aom
brew apr
brew apr-util
brew argon2
brew aspell
brew atuin
brew autoconf
brew awk
brew bat
brew berkeley-db@5
brew brotli
brew ca-certificates
brew cairo
brew coreutils
brew curl
brew dprint
brew erlang
brew findutils
brew fontconfig
brew freetds
brew freetype
brew fribidi
brew gd
brew gdbm
brew gdk-pixbuf
brew gettext
brew gh
brew giflib
brew git
brew git-absorb
brew gleam
brew glib
brew gmp
brew graphite2
brew graphviz
brew grep
brew gts
brew harfbuzz
brew highway
brew hub
brew icu4c
brew imath
brew jasper
brew jpeg-turbo
brew jpeg-xl
brew jq
brew krb5
brew libavif
brew libgit2
brew libidn2
brew libnghttp2
brew libpng
brew libpq
brew librsvg
brew libsodium
brew libssh2
brew libtiff
brew libtool
brew libunistring
brew libvmaf
brew libx11
brew libxau
brew libxcb
brew libxdmcp
brew libxext
brew libxrender
brew libyaml
brew libzip
brew little-cms2
brew lua
brew lz4
brew lzo
brew m4
brew mas
brew mpdecimal
brew ncurses
brew netpbm
brew nvm
brew oniguruma
brew openexr
brew openldap
brew openssl@3
brew pango
brew pcre
brew pcre2
brew perl
brew php
brew pixman
brew python-setuptools
brew python@3.12
brew rcm
brew readline
brew rebar3
brew ripgrep
brew rtmpdump
brew ruby
brew sqlite
brew starship
brew terminal-notifier
brew tidy-html5
brew trash
brew unixodbc
brew vim
brew webp
brew wget
brew wxwidgets
brew xorgproto
brew xz
brew z
brew zsh
brew zstd

tap homebrew/cask
cask 1password
cask 1password-cli
cask activitywatch
cask alfred
cask audacity
cask daisydisk
cask discord
cask docker
cask element
cask font-0xproto-nerd-font
cask font-3270-nerd-font
cask font-bigblue-terminal-nerd-font
cask font-bitstream-vera-sans-mono-nerd-font
cask font-blex-mono-nerd-font
cask font-caskaydia-cove-nerd-font
cask font-envy-code-r-nerd-font
cask font-fira-code-nerd-font
cask font-geist-mono-nerd-font
cask font-hasklig
cask font-hasklug-nerd-font
cask font-inconsolata-for-powerline
cask font-jetbrains-mono-nerd-font
cask font-lilex-nerd-font
cask font-profont-nerd-font
cask font-raleway
cask font-roboto-mono-nerd-font
cask font-unifrakturcook
cask font-victor-mono
cask font-victor-mono-nerd-font
cask fork
cask google-chrome
cask gpg-suite-no-mail
cask hazel
cask iterm2
cask keet
cask launchcontrol
cask marked
cask notion
cask obsidian
cask orion
cask sip
cask sketch
cask slack
cask the-unarchiver
cask visual-studio-code
cask vivaldi
cask zoom

tap homebrew/cask-fonts

tap homebrew/cask-versions

tap github/gh

tap rcmdnk/file
brew brew-file

tap thoughtbot/formulae

tap withgraphite/tap

# Other Cask applications
cask kaleidoscope2

# App Store applications
appstore 1470584107 Dato (5.3.0)
appstore 682658836 GarageBand (10.4.8)
appstore 408981434 iMovie (10.3.6)
appstore 409183694 Keynote (13.1)
appstore 409203825 Numbers (13.1)
appstore 490179405 Okta Verify (9.17.2)
appstore 409201541 Pages (13.1)
appstore 639968404 Parcel (7.11)
appstore 585829637 Todoist (9.3.3)
