
# tap repositories and their packages

tap homebrew/core
brew bat
brew coreutils
brew findutils
brew hub
brew jq
brew mas
brew nvm
brew rcm
brew starship
brew terminal-notifier
brew vim
brew wget
brew z

tap homebrew/cask-fonts
cask font-fira-code-nerd-font
cask font-hasklig
cask font-hasklug-nerd-font
cask font-inconsolata-for-powerline
cask font-raleway
cask font-victor-mono

tap homebrew/cask-versions
cask kaleidoscope2

tap homebrew/cask
cask alfred
cask audacity
cask dash
cask discord
cask fork
cask gpg-suite-no-mail
cask hazel
cask iterm2
cask launchcontrol
cask marked
cask obsidian
cask sip
cask slack
cask the-unarchiver
cask visual-studio-code
cask vivaldi

tap github/gh

tap rcmdnk/file
brew brew-file

tap thoughtbot/formulae

tap withgraphite/tap
