
# tap repositories and their packages

tap homebrew/core
brew adns
brew antigen
brew autoconf
brew autoconf-archive
brew automake
brew bat
brew boost
brew cairo
brew ccache
brew check
brew clang-format
brew cmake
brew cowsay
brew cppcheck
brew curl
brew dfu-util
brew dos2unix
brew doxygen
brew fontconfig
brew fortune
brew freetype
brew gdbm
brew gettext
brew gh
brew gifsicle
brew git
brew git-extras
brew git-lfs
brew glib
brew glibmm
brew gmp
brew gnutls
brew gputils
brew grep
brew hub
brew hyperfine
brew icu4c
brew kaitai-struct-compiler
brew libassuan
brew libevent
brew libffi
brew libftdi
brew libgcrypt
brew libgpg-error
brew libidn2
brew libksba
brew libpng
brew librtlsdr
brew libsigc++
brew libssh2
brew libtasn1
brew libtool
brew libunistring
brew libusb
brew libyaml
brew libzip
brew llvm
brew lua
brew luarocks
brew mas
brew maven
brew media-info
brew nettle
brew nmap
brew nnn
brew node
brew npth
brew onefetch
brew openssl@1.1
brew p11-kit
brew p7zip
brew pcre
brew perl
brew pinentry
brew pixman
brew pkg-config
brew platformio
brew postgresql
brew python
brew qt
brew readline
brew redis
brew ruby
brew sdcc
brew shfmt
brew socat
brew source-highlight
brew sphinx-doc
brew sqlite
brew ssh-copy-id
brew starship
brew swig
brew terminal-notifier
brew tmux
brew unbound
brew uncrustify
brew unrar
brew vagrant-completion
brew vim
brew wget
brew wmctrl
brew xz
brew yarn
brew z
brew zsh

tap homebrew/cask-drivers
cask wch-ch34x-usb-serial-driver

tap homebrew/cask-fonts
cask font-fira-mono-for-powerline
cask font-hasklig
cask font-inconsolata-for-powerline
cask font-raleway
cask font-roboto
cask font-roboto-condensed
cask font-roboto-mono
cask font-roboto-mono-for-powerline
cask font-roboto-slab
cask font-source-code-pro
cask font-victor-mono

tap caskroom/cask

tap caskroom/fonts

tap caskroom/fonts

tap github/gh

tap jesseduffield/lazygit

tap nektos/tap
brew act

tap pothosware/homebrew-pothos

tap rcmdnk/file
brew brew-file

tap rene-dev/homebrew-sigrok

tap thoughtbot/formulae
brew rcm

# Other Homebrew packages
brew gpg
brew openssl
brew python3
brew python@2
brew qt5
brew rustup
brew soapyrtlsdr
brew soapysdr

# Other Cask applications
cask 1password
cask authy
cask bartender
cask battle-net
cask bettertouchtool
cask bluemix-cli
cask calibre
cask coolterm
cask cubicsdr
cask dash
cask discord
cask fork
cask ghost
cask gitter
cask google-chrome
cask gpg-suite
cask gqrx
cask graphiql
cask handbrake
cask imageoptim
cask inkscape
cask irccloud
cask iterm2
cask java
cask jing
cask karabiner-elements
cask lastfm
cask launchcontrol
cask marked
cask mqttfx
cask nfov
cask nordvpn
cask openttd
cask pinta
cask powermate
cask qgroundcontrol
cask sauce-connect
cask sketch
cask sketchpacks
cask sketchup
cask skype
cask sourcetree
cask steam
cask sweet-home3d
cask the-unarchiver
cask twitch
cask vagrant
cask virtualbox
cask visual-studio-code
cask vivaldi
cask vlc
cask wireshark
cask xquartz

# App Store applications
appstore 411643860 DaisyDisk (4.6)
appstore 562184107 LanScan Pro (5.0)
appstore 926036361 LastPass (3.25.0)
appstore 915542151 Monity (1.4.1)
appstore 639968404 Parcel (3.2)
appstore 880001334 Reeder (3.1.2)
appstore 926319434 Stars (5.1.2)
appstore 497799835 Xcode (9.3.1)
