
# tap repositories and their packages

tap homebrew/core
brew adns
brew antigen
brew autoconf
brew autoconf-archive
brew automake
brew boost
brew cairo
brew ccache
brew check
brew clang-format
brew cmake
brew cowsay
brew cppcheck
brew curl
brew dos2unix
brew doxygen
brew fontconfig
brew fortune
brew freetype
brew gdbm
brew gettext
brew git
brew git-extras
brew glib
brew glibmm
brew gmp
brew gnutls
brew gputils
brew hub
brew icu4c
brew libassuan
brew libevent
brew libffi
brew libftdi
brew libgcrypt
brew libgpg-error
brew libidn2
brew libksba
brew libpng
brew librtlsdr
brew libsigc++
brew libtasn1
brew libtool
brew libunistring
brew libusb
brew libyaml
brew libzip
brew mas
brew maven
brew media-info
brew nettle
brew nmap
brew nnn
brew node
brew npth
brew openssl
brew p11-kit
brew p7zip
brew pcre
brew perl
brew pinentry
brew pixman
brew pkg-config
brew platformio
brew postgresql
brew python
brew python@2
brew qt
brew readline
brew redis
brew ruby
brew sdcc
brew shfmt
brew socat
brew source-highlight
brew sphinx-doc
brew sqlite
brew ssh-copy-id
brew swig
brew terminal-notifier
brew tmux
brew uncrustify
brew unrar
brew vagrant-completion
brew vim
brew wget
brew wmctrl
brew xz
brew z
brew zsh

tap caskroom/cask

tap caskroom/fonts

tap caskroom/fonts

tap jesseduffield/lazygit

tap pothosware/homebrew-pothos

tap rcmdnk/file
brew brew-file

tap thoughtbot/formulae
brew rcm

# Other Homebrew packages
brew python3
brew qt5
brew soapyrtlsdr
brew soapysdr

# Other Cask applications
cask 1password
cask alfred
cask authy
cask bartender
cask battle-net
cask bettertouchtool
cask bluemix-cli
cask calibre
cask coolterm
cask cubicsdr
cask dash
cask discord
cask dropbox
cask font-fira-mono-for-powerline
cask font-fira-mono-for-powerline
cask font-hasklig
cask font-hasklig
cask font-inconsolata-for-powerline
cask font-inconsolata-for-powerline
cask font-raleway
cask font-roboto
cask font-roboto
cask font-roboto-condensed
cask font-roboto-condensed
cask font-roboto-mono
cask font-roboto-mono
cask font-roboto-mono-for-powerline
cask font-roboto-mono-for-powerline
cask font-roboto-slab
cask font-roboto-slab
cask font-source-code-pro
cask font-source-code-pro
cask ghost
cask gitter
cask google-chrome
cask gpg-suite
cask gqrx
cask graphiql
cask handbrake
cask inkscape
cask iterm2
cask java
cask jing
cask karabiner-elements
cask keybase
cask lastfm
cask launchcontrol
cask marked
cask mqttfx
cask openttd
cask powermate
cask qgroundcontrol
cask sauce-connect
cask sketch
cask sketchpacks
cask sketchup
cask skype
cask sourcetree
cask steam
cask sweet-home3d
cask the-unarchiver
cask twitch
cask vagrant
cask virtualbox
cask visual-studio-code
cask vivaldi
cask vlc
cask wireshark
cask xquartz

# App Store applications
appstore 411643860 DaisyDisk (4.6)
appstore 562184107 LanScan Pro (5.0)
appstore 926036361 LastPass (3.25.0)
appstore 915542151 Monity (1.4.1)
appstore 639968404 Parcel (3.2)
appstore 880001334 Reeder (3.1.2)
appstore 926319434 Stars (5.1.2)
appstore 497799835 Xcode (9.3.1)
