[character]
symbol = '$'

[dotnet]
disabled = true

[golang]
disabled = true

[kubernetes]
disabled = true

[nix_shell]
disabled = false

[java]
disabled = true

[ruby]
disabled = true

[rust]
disabled = false
